name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 1.0.0.1
    - 8.8.8.8
    - 8.8.4.4
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 208.67.220.220
    - 94.140.14.14
    - 94.140.15.15
    - 64.6.64.6
    - 64.6.65.6
    - 84.200.69.80
    - 84.200.70.40
    - 76.76.19.19
    - 76.223.122.150
    - 8.26.56.26
    - 8.20.247.20
  nameserver:
    - https://cloudflare-dns.com/dns-query
    - https://1.1.1.1/dns-query
    - https://1.0.0.1/dns-query
    - https://dns.google/dns-query
    - https://8.8.8.8/dns-query
    - https://8.8.4.4/dns-query
    - https://dns.quad9.net/dns-query
    - https://9.9.9.9/dns-query
    - https://149.112.112.112/dns-query
    - https://dns.adguard.com/dns-query
    - https://94.140.14.14/dns-query
    - https://94.140.15.15/dns-query
    - https://doh.opendns.com/dns-query
    - https://208.67.222.222/dns-query
    - https://208.67.220.220/dns-query
    - https://doh.comodo.com/dns-query
    - https://8.26.56.26/dns-query
    - https://8.20.247.20/dns-query
    - https://doh.mullvad.net/dns-query
    - https://doh.dns.mullvad.net/dns-query
    - https://freedns.controld.com/p0
    - https://freedns.controld.com/family
    - tls://1.1.1.1:853
    - tls://1.0.0.1:853
    - tls://8.8.8.8:853
    - tls://8.8.4.4:853
    - tls://9.9.9.9:853
    - tls://149.112.112.112:853
    - tls://94.140.14.14:853
    - tls://94.140.15.15:853
    - tls://208.67.222.222:853
    - tls://208.67.220.220:853
    - tls://family-filter-dns.cleanbrowsing.org:853
    - tls://adult-filter-dns.cleanbrowsing.org:853
    - tls://security-filter-dns.cleanbrowsing.org:853
    - 1.1.1.1
    - 1.0.0.1
    - 8.8.8.8
    - 8.8.4.4
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 208.67.220.220
    - 94.140.14.14
    - 94.140.15.15
    - 64.6.64.6
    - 64.6.65.6
    - 84.200.69.80
    - 84.200.70.40
    - 8.26.56.26
    - 8.20.247.20
    - 76.76.19.19
    - 76.223.122.150
    - 208.67.222.123
    - 208.67.220.123
    - 195.46.39.39
    - 195.46.39.40
    - 38.132.106.139
    - 194.187.251.67

proxies:
  - name: "@DeltaKroneckerGithub"
    type: hysteria2
    server: "nl1.xiaoliyu.cyou"
    port: 4433
    password: "a4c1b618-024a-42d4-b78a-1c25c337a484"
    sni: "nl1.xiaoliyu.cyou"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub"
    type: hysteria2
    server: "45.15.171.80"
    port: 444
    password: "strong-secret-pass-777"
    sni: "www.microsoft.com"
    skip-cert-verify: true
    udp: true
    obfs: "salamander"
    obfs-password: "cry_me_a_r1ver_2026"
  - name: "@DeltaKroneckerGithub"
    type: hysteria2
    server: "103.62.49.76"
    port: 35000
    password: "38428a74-c651-47a5-b2c9-4bec5a1809cf"
    sni: "www.apple.com"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub"
    type: hysteria2
    server: "144.31.224.14"
    port: 443
    password: "123456789StrongPass"
    sni: "www.cloudflare.com"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub"
    type: hysteria2
    server: "de1.xiaoliyu.cyou"
    port: 4433
    password: "a4c1b618-024a-42d4-b78a-1c25c337a484"
    sni: "de1.xiaoliyu.cyou"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub"
    type: hysteria2
    server: "vpn-us-018.fastervpn.world"
    port: 443
    password: "qQe1z5kU8kN6SlKnDt9Ru3Qp"
    sni: "vpn-us-018.fastervpn.world"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub"
    type: hysteria2
    server: "hkaws.ccwink.photos"
    port: 88
    password: "9e0f72bb-7ad6-4383-994a-497569a94d74"
    sni: "hkak.ccwink.cc"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub"
    type: hysteria2
    server: "156.226.173.8"
    port: 8443
    password: "9c23940e-efd8-4763-bfb5-54739b50893d"
    sni: "hy5.hy2yydsapi.top"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub"
    type: hysteria2
    server: "45.192.195.52"
    port: 5555
    password: "3286b74d-a633-401f-8e22-6e8e61c5f1d9"
    sni: "45.192.195.52"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub"
    type: hysteria2
    server: "kr.ccwink.cc"
    port: 56309
    password: "9e0f72bb-7ad6-4383-994a-497569a94d74"
    sni: "kr.ccwink.cc"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub"
    type: hysteria2
    server: "94.131.101.19"
    port: 444
    password: "strong-secret-pass-777"
    sni: "www.microsoft.com"
    skip-cert-verify: true
    udp: true
    obfs: "salamander"
    obfs-password: "cry_me_a_r1ver_2026"
  - name: "@DeltaKroneckerGithub"
    type: hysteria2
    server: "45.12.134.57"
    port: 444
    password: "strong-secret-pass-777"
    sni: "www.microsoft.com"
    skip-cert-verify: true
    udp: true
    obfs: "salamander"
    obfs-password: "cry_me_a_r1ver_2026"
  - name: "@DeltaKroneckerGithub"
    type: hysteria2
    server: "62.210.124.146"
    port: 22000
    password: "dongtaiwang.com"
    sni: "www.microsoft.com"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub"
    type: hysteria2
    server: "37.114.49.38"
    port: 2056
    password: "4d092122-268a-4a1a-b23f-83931c5abc3a"
    sni: "37.114.49.38"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub"
    type: hysteria2
    server: "hjnd.0101.pw"
    port: 8444
    password: "6987a475-97a5-40ce-90fe-a59a21aa1c08"
    sni: "hjnd.0101.pw"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub"
    type: hysteria2
    server: "jpaws.ccwink.photos"
    port: 58
    password: "9e0f72bb-7ad6-4383-994a-497569a94d74"
    sni: "moak.ccwink.cc"
    skip-cert-verify: true
    udp: true
  - name: "@DeltaKroneckerGithub"
    type: hysteria2
    server: "vpn-us-021.fastervpn.world"
    port: 443
    password: "qQe1z5kU8kN6SlKnDt9Ru3Qp"
    sni: "vpn-us-021.fastervpn.world"
    skip-cert-verify: true
    udp: true

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Fallback"
      - "Auto"
      - "Load Balance"
    

  - name: "Load Balance"
    type: load-balance
    strategy: consistent-hashing
    url: http://www.gstatic.com/generate_204
    interval: 60
    tolerance: 50
    lazy: true
    proxies:
      - "@DeltaKroneckerGithub"
      - "@DeltaKroneckerGithub"
      - "@DeltaKroneckerGithub"
      - "@DeltaKroneckerGithub"
      - "@DeltaKroneckerGithub"
      - "@DeltaKroneckerGithub"
      - "@DeltaKroneckerGithub"
      - "@DeltaKroneckerGithub"
      - "@DeltaKroneckerGithub"
      - "@DeltaKroneckerGithub"
      - "@DeltaKroneckerGithub"
      - "@DeltaKroneckerGithub"
      - "@DeltaKroneckerGithub"
      - "@DeltaKroneckerGithub"
      - "@DeltaKroneckerGithub"
      - "@DeltaKroneckerGithub"
      - "@DeltaKroneckerGithub"

  - name: "Auto"
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 60
    tolerance: 50
    lazy: true
    proxies:
      - "@DeltaKroneckerGithub"
      - "@DeltaKroneckerGithub"
      - "@DeltaKroneckerGithub"
      - "@DeltaKroneckerGithub"
      - "@DeltaKroneckerGithub"
      - "@DeltaKroneckerGithub"
      - "@DeltaKroneckerGithub"
      - "@DeltaKroneckerGithub"
      - "@DeltaKroneckerGithub"
      - "@DeltaKroneckerGithub"
      - "@DeltaKroneckerGithub"
      - "@DeltaKroneckerGithub"
      - "@DeltaKroneckerGithub"
      - "@DeltaKroneckerGithub"
      - "@DeltaKroneckerGithub"
      - "@DeltaKroneckerGithub"
      - "@DeltaKroneckerGithub"

  - name: "Fallback"
    type: fallback
    url: http://www.gstatic.com/generate_204
    interval: 60
    lazy: true
    proxies:
      - "@DeltaKroneckerGithub"
      - "@DeltaKroneckerGithub"
      - "@DeltaKroneckerGithub"
      - "@DeltaKroneckerGithub"
      - "@DeltaKroneckerGithub"
      - "@DeltaKroneckerGithub"
      - "@DeltaKroneckerGithub"
      - "@DeltaKroneckerGithub"
      - "@DeltaKroneckerGithub"
      - "@DeltaKroneckerGithub"
      - "@DeltaKroneckerGithub"
      - "@DeltaKroneckerGithub"
      - "@DeltaKroneckerGithub"
      - "@DeltaKroneckerGithub"
      - "@DeltaKroneckerGithub"
      - "@DeltaKroneckerGithub"
      - "@DeltaKroneckerGithub"

rules:
  - MATCH,PROXY
