name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 1.0.0.1
    - 8.8.8.8
    - 8.8.4.4
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 208.67.220.220
    - 94.140.14.14
    - 94.140.15.15
    - 64.6.64.6
    - 64.6.65.6
    - 84.200.69.80
    - 84.200.70.40
    - 76.76.19.19
    - 76.223.122.150
    - 8.26.56.26
    - 8.20.247.20
  nameserver:
    - https://cloudflare-dns.com/dns-query
    - https://1.1.1.1/dns-query
    - https://1.0.0.1/dns-query
    - https://dns.google/dns-query
    - https://8.8.8.8/dns-query
    - https://8.8.4.4/dns-query
    - https://dns.quad9.net/dns-query
    - https://9.9.9.9/dns-query
    - https://149.112.112.112/dns-query
    - https://dns.adguard.com/dns-query
    - https://94.140.14.14/dns-query
    - https://94.140.15.15/dns-query
    - https://doh.opendns.com/dns-query
    - https://208.67.222.222/dns-query
    - https://208.67.220.220/dns-query
    - https://doh.comodo.com/dns-query
    - https://8.26.56.26/dns-query
    - https://8.20.247.20/dns-query
    - https://doh.mullvad.net/dns-query
    - https://doh.dns.mullvad.net/dns-query
    - https://freedns.controld.com/p0
    - https://freedns.controld.com/family
    - tls://1.1.1.1:853
    - tls://1.0.0.1:853
    - tls://8.8.8.8:853
    - tls://8.8.4.4:853
    - tls://9.9.9.9:853
    - tls://149.112.112.112:853
    - tls://94.140.14.14:853
    - tls://94.140.15.15:853
    - tls://208.67.222.222:853
    - tls://208.67.220.220:853
    - tls://family-filter-dns.cleanbrowsing.org:853
    - tls://adult-filter-dns.cleanbrowsing.org:853
    - tls://security-filter-dns.cleanbrowsing.org:853
    - 1.1.1.1
    - 1.0.0.1
    - 8.8.8.8
    - 8.8.4.4
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 208.67.220.220
    - 94.140.14.14
    - 94.140.15.15
    - 64.6.64.6
    - 64.6.65.6
    - 84.200.69.80
    - 84.200.70.40
    - 8.26.56.26
    - 8.20.247.20
    - 76.76.19.19
    - 76.223.122.150
    - 208.67.222.123
    - 208.67.220.123
    - 195.46.39.39
    - 195.46.39.40
    - 38.132.106.139
    - 194.187.251.67

proxies:
  - name: "@rossinna77Github"
    type: trojan
    server: "104.18.152.210"
    port: 443
    password: "humanity"
    sni: "www.ignitelimit.com"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/assignment"
      headers:
        Host: "www.ignitelimit.com"
  - name: "@rossinna77Github"
    type: vless
    server: "157.22.181.104"
    port: 443
    uuid: "5d8fcd24-9634-4dd7-845c-3dc2d6291942"
    udp: true
    flow: "xtls-rprx-vision"
    tls: true
    skip-cert-verify: false
    servername: "www.google.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "2fgsbEAn-ALVpjnE4ZTPrzaZY70vVplYwldCnslInE0"
      short-id: "86b80f1e713a33ad"
  - name: "@rossinna77Github"
    type: vless
    server: "172.64.146.138"
    port: 443
    uuid: "fc965ad9-bdd7-4815-ad71-b39ec5972dc1"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "octopusss4.com"
    alpn: ["http/1.1"]
    network: ws
    ws-opts:
      path: "/tsghdws"
      headers:
        Host: "octopusss4.com"
  - name: "@rossinna77Github"
    type: vless
    server: "51.91.103.142"
    port: 2053
    uuid: "5a23e6b2-3cd3-4475-898e-0885d71da6ec"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "us2.wxgqlfx.xyz"
    client-fingerprint: "chrome"
    alpn: ["http/1.1"]
    network: ws
    ws-opts:
      path: "/TG@wxgqlfx"
      headers:
        Host: "us2.wxgqlfx.xyz"
  - name: "@rossinna77Github"
    type: vless
    server: "94.159.100.136"
    port: 443
    uuid: "5a23e6b2-3cd3-4475-898e-0885d71da6ec"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "us2.wxgqlfx.xyz"
    client-fingerprint: "chrome"
    alpn: ["http/1.1"]
    network: ws
    ws-opts:
      path: "/TG@wxgqlfx"
      headers:
        Host: "us2.wxgqlfx.xyz"
  - name: "@rossinna77Github"
    type: vless
    server: "172.235.49.135"
    port: 17973
    uuid: "5a23e6b2-3cd3-4475-898e-0885d71da6ec"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "us2.wxgqlfx.xyz"
    client-fingerprint: "chrome"
    alpn: ["http/1.1"]
    network: ws
    ws-opts:
      path: "/TG@wxgqlfx"
      headers:
        Host: "us2.wxgqlfx.xyz"
  - name: "@rossinna77Github"
    type: vless
    server: "152.228.134.48"
    port: 2053
    uuid: "5a23e6b2-3cd3-4475-898e-0885d71da6ec"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "us2.wxgqlfx.xyz"
    client-fingerprint: "chrome"
    alpn: ["http/1.1"]
    network: ws
    ws-opts:
      path: "/TG@wxgqlfx"
      headers:
        Host: "us2.wxgqlfx.xyz"
  - name: "@rossinna77Github"
    type: trojan
    server: "65.20.90.225"
    port: 443
    password: "Tu1fZjElnkRg0ECRj0sI0u54PY8ptUmATg"
    sni: "www.sandbox-cloud.click"
    skip-cert-verify: true
    udp: true
  - name: "@rossinna77Github"
    type: trojan
    server: "ch-2.bexum.fun"
    port: 443
    password: "LYaEYwjN8LjWTRJdCCTzW7V6gK7atJVu"
    sni: "ch-2.bexum.fun"
    skip-cert-verify: true
    udp: true
  - name: "@rossinna77Github"
    type: vless
    server: "172.64.53.240"
    port: 443
    uuid: "77777777-8a3e-6666-b6d1-a9c5f0e8b3a2"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "fgnix832fx.fx6hsv0.ccwu.cc"
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "fgnix832fx.fx6hsv0.ccwu.cc"
  - name: "@rossinna77Github"
    type: trojan
    server: "v2.dabache.top"
    port: 443
    password: "87d1bfd4-574e-4c96-ad42-0426f27461ff"
    sni: "_acme-challenge.sb.cloudns.biz"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "_acme-challenge.sb.cloudns.biz"
  - name: "@rossinna77Github"
    type: vless
    server: "cdn.sg3.cocoduck.org"
    port: 19609
    uuid: "4dd69f91-190c-413d-88c7-2f1675a98d85"
    udp: true
    flow: "xtls-rprx-vision"
    tls: true
    skip-cert-verify: false
    servername: "www.apple.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "VoA8WXthSh6CroV4pHK7V6L5gYUw8MHTo2kIVknTXSE"
      short-id: "693b25e06841ac7f"
  - name: "@rossinna77Github"
    type: vless
    server: "152.67.209.237"
    port: 22053
    uuid: "5a23e6b2-3cd3-4475-898e-0885d71da6ec"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "us2.wxgqlfx.xyz"
    client-fingerprint: "chrome"
    alpn: ["http/1.1"]
    network: ws
    ws-opts:
      path: "/TG@wxgqlfx"
      headers:
        Host: "us2.wxgqlfx.xyz"
  - name: "@rossinna77Github"
    type: vless
    server: "62.210.91.2"
    port: 23576
    uuid: "48ff2b70-e180-582f-8866-d9a2edeed5f5"
    udp: true
    flow: "xtls-rprx-vision"
    tls: true
    skip-cert-verify: false
    servername: "fuck.rkn"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "1y5h2FGWKXTJ9xLPCqPo6Mw7RxoZzh6fGkEQKNxpZ3s"
      short-id: "01"
  - name: "@rossinna77Github"
    type: vless
    server: "172.66.213.38"
    port: 443
    uuid: "50b43435-6bb5-45ef-aff7-85f3844ba039"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "click.snapchat.com.r3xxe.eu.cc"
    network: ws
    ws-opts:
      path: "/au-mt"
      headers:
        Host: "click.snapchat.com.r3xxe.eu.cc"
  - name: "@rossinna77Github"
    type: vless
    server: "31.76.91.29"
    port: 443
    uuid: "dfc0cb9d-f005-41b0-848c-7703bd39d0de"
    udp: true
    flow: "xtls-rprx-vision"
    tls: true
    skip-cert-verify: false
    servername: "jp.s3-cloud.org"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "QVkd5uoSbUA7rHVLtIoJB4iRp4l0zuw0H9qzQBh3lHs"
      short-id: "7a3f9e2b1c8d4f6a"
  - name: "@rossinna77Github"
    type: vless
    server: "31.76.113.101"
    port: 443
    uuid: "dfc0cb9d-f005-41b0-848c-7703bd39d0de"
    udp: true
    flow: "xtls-rprx-vision"
    tls: true
    skip-cert-verify: false
    servername: "it.s3-cloud.xyz"
    client-fingerprint: "edge"
    reality-opts:
      public-key: "zPi2L9vrl2hkaCTT3lZTzBna-qz6JrteRjDz1i-DsxY"
      short-id: "7a3f9e2b1c8d4f6a"
  - name: "@rossinna77Github"
    type: vless
    server: "staging.lastilhame.monster"
    port: 443
    uuid: "317bc783-340f-453c-afb5-b6bf637c0b23"
    udp: true
    flow: "xtls-rprx-vision"
    tls: true
    skip-cert-verify: false
    servername: "www.tradingview.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "FjcEZNQ8t5E4R04_11T6ghsOutdqwKKrelkuadakoQg"
      short-id: "fc994ae7eb10"
  - name: "@rossinna77Github"
    type: vless
    server: "169.150.228.24"
    port: 8443
    uuid: "394f6981-a782-4779-9a85-e6cf22935d93"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "bog-co-01.fromblancwithlove.com"
  - name: "@rossinna77Github"
    type: vless
    server: "107.181.151.241"
    port: 443
    uuid: "106d20f6-d70a-40e2-b69b-8e82baf8d117"
    udp: true
    flow: "xtls-rprx-vision"
    tls: true
    skip-cert-verify: false
    servername: "www.microsoft.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "FjcEZNQ8t5E4R04_11T6ghsOutdqwKKrelkuadakoQg"
      short-id: "60500a63ad12"
  - name: "@rossinna77Github"
    type: vless
    server: "195.74.93.254"
    port: 443
    uuid: "451ccfb4-4d9f-4d16-a748-48862ff46b86"
    udp: true
    flow: "xtls-rprx-vision"
    tls: true
    skip-cert-verify: false
    servername: "web.max.ru"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "7ReQIe2kMtP4rCrptgH5glkOM-JGcSAPzHNxOED-Z0s"
      short-id: "247fd6dab1a34a48"
  - name: "@rossinna77Github"
    type: trojan
    server: "104.18.152.73"
    port: 443
    password: "humanity"
    sni: "www.ignitelimit.com"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/assignment"
      headers:
        Host: "www.ignitelimit.com"
  - name: "@rossinna77Github"
    type: vless
    server: "31.76.113.116"
    port: 443
    uuid: "dfc0cb9d-f005-41b0-848c-7703bd39d0de"
    udp: true
    flow: "xtls-rprx-vision"
    tls: true
    skip-cert-verify: false
    servername: "it.s3-cloud.xyz"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "zPi2L9vrl2hkaCTT3lZTzBna-qz6JrteRjDz1i-DsxY"
      short-id: "7a3f9e2b1c8d4f6a"
  - name: "@rossinna77Github"
    type: vless
    server: "172.64.53.87"
    port: 2087
    uuid: "77777777-8a3e-6666-b6d1-a9c5f0e8b3a2"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "fgnix832fx.fx6hsv0.ccwu.cc"
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "fgnix832fx.fx6hsv0.ccwu.cc"
  - name: "@rossinna77Github"
    type: trojan
    server: "89.116.46.8"
    port: 443
    password: "humanity"
    sni: "www.calmloud.com"
    skip-cert-verify: true
    udp: true
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/assignment"
      headers:
        Host: "www.calmloud.com"
  - name: "@rossinna77Github"
    type: vless
    server: "31.76.113.14"
    port: 443
    uuid: "dfc0cb9d-f005-41b0-848c-7703bd39d0de"
    udp: true
    flow: "xtls-rprx-vision"
    tls: true
    skip-cert-verify: false
    servername: "it.s3-cloud.xyz"
    client-fingerprint: "edge"
    reality-opts:
      public-key: "zPi2L9vrl2hkaCTT3lZTzBna-qz6JrteRjDz1i-DsxY"
      short-id: "7a3f9e2b1c8d4f6a"
  - name: "@rossinna77Github"
    type: trojan
    server: "155.117.198.86"
    port: 45619
    password: "4f4d1167-ef14-4304-9bce-0740472503ef"
    sni: "fr.01.naiun.bilibili.com"
    skip-cert-verify: true
    udp: true
  - name: "@rossinna77Github"
    type: trojan
    server: "91.233.8.25"
    port: 443
    password: "I1vtf6pjYsAu-nFnraWAMjKTy90AHitdAz"
    sni: "fra34.tracker-ws.click"
    skip-cert-verify: true
    udp: true
    client-fingerprint: "chrome"
  - name: "@rossinna77Github"
    type: vless
    server: "de2.niekotin.de"
    port: 80
    uuid: "12e2b366-6426-4e09-9c6f-9c894262b923"
    udp: true
    network: ws
    ws-opts:
      path: "/vless"
  - name: "@rossinna77Github"
    type: vless
    server: "104.21.80.17"
    port: 443
    uuid: "a6f1755f-0140-4bea-8727-0db1bed7c4df"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "juzi.qea.ccwu.cc"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/?ed=2048"
      headers:
        Host: "juzi.qea.ccwu.cc"
  - name: "@rossinna77Github"
    type: trojan
    server: "109.234.211.66"
    port: 8443
    password: "trojan"
    sni: "store.timimi.dpdns.org"
    skip-cert-verify: true
    udp: true
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "store.timimi.dpdns.org"
  - name: "@rossinna77Github"
    type: trojan
    server: "adak.sonofthewinds.com"
    port: 34436
    password: "825929f4-c702-35ce-9124-00d3f95b8c32"
    sni: "hh4.sonofthewinds.com"
    skip-cert-verify: true
    udp: true
  - name: "@rossinna77Github"
    type: vless
    server: "151.115.164.36"
    port: 8880
    uuid: "8dc7722c-2767-4eea-a28b-2f8daacc07e3"
    udp: true
    network: grpc
    grpc-opts:
      grpc-service-name: ""

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Fallback"
      - "Auto"
      - "Load Balance"
    

  - name: "Load Balance"
    type: load-balance
    strategy: consistent-hashing
    url: http://www.gstatic.com/generate_204
    interval: 60
    tolerance: 50
    lazy: true
    proxies:
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"

  - name: "Auto"
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 60
    tolerance: 50
    lazy: true
    proxies:
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"

  - name: "Fallback"
    type: fallback
    url: http://www.gstatic.com/generate_204
    interval: 60
    lazy: true
    proxies:
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"

rules:
  - MATCH,PROXY
