name: "Standard"
mixed-port: 7890
socks-port: 7891
port: 7892
allow-lan: true
bind-address: '*'
mode: global
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
external-ui: ui
secret: ""
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
find-process-mode: strict
keep-alive-interval: 15

profile:
  store-selected: true
  store-fake-ip: false

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:5353
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.local'
    - '*.lan'
    - '*.localhost'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'time.*'
    - 'time.*.com'
    - 'connectivitycheck.gstatic.com'
    - 'detectportal.firefox.com'
    - 'captive.apple.com'
    - 'www.msftncsi.com'
    - 'cp.cloudflare.com'
  default-nameserver:
    - 1.1.1.1
    - 1.0.0.1
    - 8.8.8.8
    - 8.8.4.4
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 208.67.220.220
    - 94.140.14.14
    - 94.140.15.15
    - 64.6.64.6
    - 64.6.65.6
    - 84.200.69.80
    - 84.200.70.40
    - 76.76.19.19
    - 76.223.122.150
    - 8.26.56.26
    - 8.20.247.20
  nameserver:
    - https://cloudflare-dns.com/dns-query
    - https://1.1.1.1/dns-query
    - https://1.0.0.1/dns-query
    - https://dns.google/dns-query
    - https://8.8.8.8/dns-query
    - https://8.8.4.4/dns-query
    - https://dns.quad9.net/dns-query
    - https://9.9.9.9/dns-query
    - https://149.112.112.112/dns-query
    - https://dns.adguard.com/dns-query
    - https://94.140.14.14/dns-query
    - https://94.140.15.15/dns-query
    - https://doh.opendns.com/dns-query
    - https://208.67.222.222/dns-query
    - https://208.67.220.220/dns-query
    - https://doh.comodo.com/dns-query
    - https://8.26.56.26/dns-query
    - https://8.20.247.20/dns-query
    - https://doh.mullvad.net/dns-query
    - https://doh.dns.mullvad.net/dns-query
    - https://freedns.controld.com/p0
    - https://freedns.controld.com/family
    - tls://1.1.1.1:853
    - tls://1.0.0.1:853
    - tls://8.8.8.8:853
    - tls://8.8.4.4:853
    - tls://9.9.9.9:853
    - tls://149.112.112.112:853
    - tls://94.140.14.14:853
    - tls://94.140.15.15:853
    - tls://208.67.222.222:853
    - tls://208.67.220.220:853
    - tls://family-filter-dns.cleanbrowsing.org:853
    - tls://adult-filter-dns.cleanbrowsing.org:853
    - tls://security-filter-dns.cleanbrowsing.org:853
    - 1.1.1.1
    - 1.0.0.1
    - 8.8.8.8
    - 8.8.4.4
    - 9.9.9.9
    - 149.112.112.112
    - 208.67.222.222
    - 208.67.220.220
    - 94.140.14.14
    - 94.140.15.15
    - 64.6.64.6
    - 64.6.65.6
    - 84.200.69.80
    - 84.200.70.40
    - 8.26.56.26
    - 8.20.247.20
    - 76.76.19.19
    - 76.223.122.150
    - 208.67.222.123
    - 208.67.220.123
    - 195.46.39.39
    - 195.46.39.40
    - 38.132.106.139
    - 194.187.251.67

proxies:
  - name: "@rossinna77Github"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "8be98cb0-0942-4bc2-b2da-eec9e2e53f9f"
    udp: true
    flow: "xtls-rprx-vision"
    tls: true
    skip-cert-verify: false
    servername: "www.sony.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "7l16WkJYuCyfJG2ayNxM-IBh8J3bZvi_ntFcjokuASg"
      short-id: "7134a1b6e13dcb36"
  - name: "@rossinna77Github"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "b54d36d1-43c3-4b8f-a5f8-cf6504db0562"
    udp: true
    tls: true
    skip-cert-verify: false
    servername: "apple.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "MbYR2O0XBSeG74gGYpFIofXsILcf5lG2gc36GyURBXQ"
      short-id: "0199436dd359351b"
    network: grpc
    grpc-opts:
      grpc-service-name: ""
  - name: "@rossinna77Github"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "e0f64e0b-ecb7-43fa-803b-99b728e54128"
    udp: true
    flow: "xtls-rprx-vision"
    tls: true
    skip-cert-verify: false
    servername: "api-maps.yandex.ru"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "MX_HmJw-Auo8vAkcyM_5C8FzdQ42PPfh-LveTdg6P3c"
      short-id: "27e53bbcab7593d2"
  - name: "@rossinna77Github"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "e4e7866d-920b-4a53-a8e2-6ae9b2a42fc2"
    udp: true
    flow: "xtls-rprx-vision"
    tls: true
    skip-cert-verify: false
    servername: "www.cloudflare.com"
    client-fingerprint: "safari"
    reality-opts:
      public-key: "trNcbZqs-1u3CDgb9-NiL4AoZTtCvaq5trvMpgBYnDQ"
      short-id: "d2f6a308"
  - name: "@rossinna77Github"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "42026ed0-7d74-4585-8e46-0fe6aa4d665a"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "www.genflix.co.id.r3xxe.eu.cc"
    network: ws
    ws-opts:
      path: "/au-do"
      headers:
        Host: "www.genflix.co.id.r3xxe.eu.cc"
  - name: "@rossinna77Github"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "48ff2b70-e180-582f-8866-d9a2edeed5f5"
    udp: true
    flow: "xtls-rprx-vision"
    tls: true
    skip-cert-verify: false
    servername: "fuck.rkn"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "1y5h2FGWKXTJ9xLPCqPo6Mw7RxoZzh6fGkEQKNxpZ3s"
      short-id: "01"
  - name: "@rossinna77Github"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "48ff2b70-e180-582f-8866-d9a2edeed5f5"
    udp: true
    flow: "xtls-rprx-vision"
    tls: true
    skip-cert-verify: false
    servername: "fuck.rkn"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "1y5h2FGWKXTJ9xLPCqPo6Mw7RxoZzh6fGkEQKNxpZ3s"
      short-id: "01"
  - name: "@rossinna77Github"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "humanity"
    sni: "www.calmloud.com"
    skip-cert-verify: true
    udp: true
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/assignment"
      headers:
        Host: "www.calmloud.com"
  - name: "@rossinna77Github"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "e5cc16a6-ea42-46b2-82ae-ad2157e1641b"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "hhlfy.twiladaphne.ndjp.net"
    client-fingerprint: "random"
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "hhlfy.twiladaphne.ndjp.net"
  - name: "@rossinna77Github"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "633ea3be-bdd9-4691-9b14-b32a024a3b22"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "unnes.ac.id.r3xxe.eu.cc"
    network: ws
    ws-opts:
      path: "/au-do"
      headers:
        Host: "unnes.ac.id.r3xxe.eu.cc"
  - name: "@rossinna77Github"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "humanity"
    sni: "www.ignitelimit.com"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/assignment"
      headers:
        Host: "www.ignitelimit.com"
  - name: "@rossinna77Github"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "46f4ee92-92df-4580-a696-4844fcb39b85"
    udp: true
    flow: "xtls-rprx-vision"
    tls: true
    skip-cert-verify: false
    servername: "www.microsoft.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "4YLfHf90V012Oyd2wHbwAXaJNvNUGrKWmatTKc165U8"
      short-id: "3a57254c6a44"
  - name: "@rossinna77Github"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "d78c12c4-6927-40b8-8550-ed9be00334da"
    udp: true
    flow: "xtls-rprx-vision"
    tls: true
    skip-cert-verify: false
    servername: "nether2cxc.ignorelist.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "MNfRDUdBmptd-zKqgIljosss5-oNO44Lt68hgVwa_Qo"
      short-id: "22f2d3f943dfcb40"
  - name: "@rossinna77Github"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "317bc783-340f-453c-afb5-b6bf637c0b23"
    udp: true
    flow: "xtls-rprx-vision"
    tls: true
    skip-cert-verify: false
    servername: "www.tradingview.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "FjcEZNQ8t5E4R04_11T6ghsOutdqwKKrelkuadakoQg"
      short-id: "fc994ae7eb10"
  - name: "@rossinna77Github"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "dfc0cb9d-f005-41b0-848c-7703bd39d0de"
    udp: true
    flow: "xtls-rprx-vision"
    tls: true
    skip-cert-verify: false
    servername: "it.s3-cloud.xyz"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "zPi2L9vrl2hkaCTT3lZTzBna-qz6JrteRjDz1i-DsxY"
      short-id: "7a3f9e2b1c8d4f6a"
  - name: "@rossinna77Github"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "a6f1755f-0140-4bea-8727-0db1bed7c4df"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "juzi.qea.ccwu.cc"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/?ed=2048"
      headers:
        Host: "juzi.qea.ccwu.cc"
  - name: "@rossinna77Github"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "e4fc4761-154f-490e-bbaa-b4fa193f1073"
    udp: true
    network: ws
    ws-opts:
      path: "/"
  - name: "@rossinna77Github"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "b7977b65-cfd8-4db9-a029-6ef014a4ae4a"
    udp: true
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "xU.aSaCO.sTorE"
  - name: "@rossinna77Github"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "950518cc-fcd4-4547-be3d-32acf65257ca"
    udp: true
    flow: "xtls-rprx-vision"
    tls: true
    skip-cert-verify: false
    servername: "www.yahoo.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "Yozi8V5IYT7TzszTYwxnxMO-RZ93qCRFpgzZYehbqiM"
      short-id: "74bc0da65781e5dd"
  - name: "@rossinna77Github"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "43488128-319e-f480-64ea-0acdc712e2a8"
    udp: true
    flow: "xtls-rprx-vision"
    tls: true
    skip-cert-verify: false
    servername: "www.booking.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "Ic2uiGhkBgJUsY0CZUBqa1y22V_BO7F4S93Zgk_ir2c"
      short-id: "a1b2c3d4e5f67890"
  - name: "@rossinna77Github"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "5a23e6b2-3cd3-4475-898e-0885d71da6ec"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "us2.wxgqlfx.xyz"
    client-fingerprint: "chrome"
    alpn: ["http/1.1"]
    network: ws
    ws-opts:
      path: "/TG@wxgqlfx"
      headers:
        Host: "us2.wxgqlfx.xyz"
  - name: "@rossinna77Github"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "bcc094e4-1a85-8a25-f8e1-5b08b9af841c"
    udp: true
    flow: "xtls-rprx-vision"
    tls: true
    skip-cert-verify: false
    servername: "stackoverflow.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "LaGTRJ1CJnnYV7FnyqQnU28I0xFTPFKI8xmUFwig5ic"
      short-id: "c410508e9721512b"
  - name: "@rossinna77Github"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "a6f1755f-0140-4bea-8727-0db1bed7c4df"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "juzi.qea.ccwu.cc"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/?ed=2048"
      headers:
        Host: "juzi.qea.ccwu.cc"
  - name: "@rossinna77Github"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "93d272cc-4c50-4347-bfc6-1cf733ce12b2"
    udp: true
    tls: true
    skip-cert-verify: false
    servername: "play.google.com"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "D8uvi--0Aq7Hjc7cYnfcJGY0h4SSBCrPh7wEp1mvFlw"
      short-id: "b7b70c104ad267b8"
  - name: "@rossinna77Github"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "17451fec-af94-4715-8c2f-7f6839130d0a"
    udp: true
    tls: true
    skip-cert-verify: false
    servername: "tradingview.com"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "LidllyozUeeSbuzJ0ZfieGoy8YjVzqXX9H2m9whPaG0"
      short-id: "53197c66aef53c44"
  - name: "@rossinna77Github"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "dfb1ab61-066c-4bce-ba32-d8fe8cc42dd7"
    udp: true
    flow: "xtls-rprx-vision"
    tls: true
    skip-cert-verify: false
    servername: "wikipedia.org"
    client-fingerprint: "chrome"
    reality-opts:
      public-key: "14mbxpFBwnpp817ZLgT-6dVqsOmNPIaH7ygYcYScjGg"
      short-id: "2b4790ccbac1edb2"
  - name: "@rossinna77Github"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "e0f64e0b-ecb7-43fa-803b-99b728e54128"
    udp: true
    flow: "xtls-rprx-vision"
    tls: true
    skip-cert-verify: false
    servername: "plfsdd.dendiboss.org"
    client-fingerprint: "firefox"
    reality-opts:
      public-key: "NtaFdDQFRPxPPIcRc-qyYDbL9mI_miwnaHcdLWvpgmo"
      short-id: "9c2378562188c3cb"
  - name: "@rossinna77Github"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "c135158e-5869-4397-8116-6695ca18cd48"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "cf.hulume.ccwu.cc"
    client-fingerprint: "chrome"
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "cf.hulume.ccwu.cc"
  - name: "@rossinna77Github"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "humanity"
    sni: "www.ignitelimit.com"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/assignment"
      headers:
        Host: "www.ignitelimit.com"
  - name: "@rossinna77Github"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "5a23e6b2-3cd3-4475-898e-0885d71da6ec"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "us2.wxgqlfx.xyz"
    client-fingerprint: "chrome"
    alpn: ["http/1.1"]
    network: ws
    ws-opts:
      path: "/TG@wxgqlfx"
      headers:
        Host: "us2.wxgqlfx.xyz"
  - name: "@rossinna77Github"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "5a23e6b2-3cd3-4475-898e-0885d71da6ec"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "us2.wxgqlfx.xyz"
    client-fingerprint: "chrome"
    alpn: ["http/1.1"]
    network: ws
    ws-opts:
      path: "/TG@wxgqlfx"
      headers:
        Host: "us2.wxgqlfx.xyz"
  - name: "@rossinna77Github"
    type: vless
    server: "127.0.0.1"
    port: 40443
    uuid: "77777777-8a3e-6666-b6d1-a9c5f0e8b3a2"
    udp: true
    tls: true
    skip-cert-verify: true
    servername: "fgnix832fx.fx6hsv0.ccwu.cc"
    network: ws
    ws-opts:
      path: "/"
      headers:
        Host: "fgnix832fx.fx6hsv0.ccwu.cc"
  - name: "@rossinna77Github"
    type: trojan
    server: "127.0.0.1"
    port: 40443
    password: "humanity"
    sni: "www.ignitelimit.com"
    skip-cert-verify: true
    udp: true
    network: ws
    ws-opts:
      path: "/assignment"
      headers:
        Host: "www.ignitelimit.com"

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "Fallback"
      - "Auto"
      - "Load Balance"
    

  - name: "Load Balance"
    type: load-balance
    strategy: consistent-hashing
    url: http://www.gstatic.com/generate_204
    interval: 60
    tolerance: 50
    lazy: true
    proxies:
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"

  - name: "Auto"
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 60
    tolerance: 50
    lazy: true
    proxies:
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"

  - name: "Fallback"
    type: fallback
    url: http://www.gstatic.com/generate_204
    interval: 60
    lazy: true
    proxies:
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"
      - "@rossinna77Github"

rules:
  - MATCH,PROXY
